name: Deploy to GitHub Pages

on:
  # Se ejecuta en push a main/master
  push:
    branches: [ "master", "main" ]

  # Permite ejecutar manualmente desde el tab Actions
  workflow_dispatch:

# Establece permisos para el GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "./out" ]; then
            echo "Error: Build output directory './out' not found"
            exit 1
          fi
          echo "Build output verified: $(ls -la ./out | wc -l) files/directories in ./out"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  # Job para deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4